[package]
name = "pwutils"
version = "0.1.0"
authors = ["alkemet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.8"
passwords = { version = "1.1.5", features = ["crypto"]}
clipboard = "0.5.0"
